name: Build GIF thumbnails

on:
  push:
    branches: [ "main" ]
    paths:
      - "A-1images/*.gif"
      - "A-2images/*.gif"
      - "Bimages/*.gif"

jobs:
  make-thumbs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Generate thumbnails
        shell: bash
        run: |
          set -e
          for DIR in A-1images A-2images Bimages; do
            if [ -d "$DIR" ]; then
              OUT="thumbs/$DIR"
              mkdir -p "$OUT"
              # 1.gif ~ 60.gif만 처리 (최대 60장 가정)
              for i in $(seq 1 60); do
                IN="$DIR/$i.gif"
                OUTPNG="$OUT/$i.png"
                if [ -f "$IN" ]; then
                  ffmpeg -v error -y -i "$IN" -frames:v 1 "$OUTPNG"
                fi
              done
            fi
          done

      - name: Commit thumbnails
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update generated thumbs"
          file_pattern: "thumbs/**"
